# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from graphics import GraphicsView, GraphicsPixmapItem



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 850)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 351, 641))
        font = QtGui.QFont()
        font.setFamily("Songti SC")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 331, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 301, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("STSong")
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_6)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.comboBox_20 = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("STSong")
        font.setPointSize(14)
        self.comboBox_20.setFont(font)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_20)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_8, 3, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_9, 4, 0, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_31.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_31.addWidget(self.label_49, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_31, 5, 0, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_32.addWidget(self.label_50, 0, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_32.addWidget(self.label_51, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_32, 6, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_33.addWidget(self.label_52, 0, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_33.addWidget(self.label_53, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_33, 7, 0, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.label_69 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_42.addWidget(self.label_69, 0, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_42.addWidget(self.label_70, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_42, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_4.addWidget(self.label_71)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("STSong")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 9, 0, 1, 1)
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_73 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_44.addWidget(self.label_73, 0, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_44.addWidget(self.label_74, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_44, 10, 0, 1, 1)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.label_75 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.gridLayout_45.addWidget(self.label_75, 0, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.gridLayout_45.addWidget(self.label_76, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_45, 11, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_124 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_124.setFont(font)
        self.label_124.setObjectName("label_124")
        self.horizontalLayout_3.addWidget(self.label_124)
        self.label_125 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_125.setFont(font)
        self.label_125.setObjectName("label_125")
        self.horizontalLayout_3.addWidget(self.label_125)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 12, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 301, 541))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_15.addWidget(self.label_28, 0, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("STSong")
        font.setPointSize(18)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_13.addWidget(self.label_29)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_9)
        self.gridLayout_14.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_14.addWidget(self.label_30)
        self.comboBox_23 = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("STSong")
        font.setPointSize(14)
        self.comboBox_23.setFont(font)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_23)
        self.gridLayout_14.addLayout(self.horizontalLayout_14, 2, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_16.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_16.addWidget(self.label_32, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_16, 3, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_17.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_17.addWidget(self.label_34, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_17, 4, 0, 1, 1)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.gridLayout_40.addWidget(self.label_66, 0, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_40.addWidget(self.label_67, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_40, 5, 0, 1, 1)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.label_68 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_41.addWidget(self.label_68, 0, 0, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_90.setFont(font)
        self.label_90.setObjectName("label_90")
        self.gridLayout_41.addWidget(self.label_90, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_41, 6, 0, 1, 1)
        self.gridLayout_51 = QtWidgets.QGridLayout()
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.label_91 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.gridLayout_51.addWidget(self.label_91, 0, 0, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.gridLayout_51.addWidget(self.label_92, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_51, 7, 0, 1, 1)
        self.gridLayout_52 = QtWidgets.QGridLayout()
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.label_93 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.gridLayout_52.addWidget(self.label_93, 0, 0, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.gridLayout_52.addWidget(self.label_94, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_52, 8, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_95 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_15.addWidget(self.label_95)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("STSong")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_15.addWidget(self.lineEdit_4)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_15.addWidget(self.label_35)
        self.gridLayout_14.addLayout(self.horizontalLayout_15, 9, 0, 1, 1)
        self.gridLayout_53 = QtWidgets.QGridLayout()
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.label_96 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.gridLayout_53.addWidget(self.label_96, 0, 0, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.gridLayout_53.addWidget(self.label_97, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_53, 10, 0, 1, 1)
        self.gridLayout_54 = QtWidgets.QGridLayout()
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.label_98 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")
        self.gridLayout_54.addWidget(self.label_98, 0, 0, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridLayout_54.addWidget(self.label_99, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_54, 11, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_130 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.horizontalLayout_16.addWidget(self.label_130)
        self.label_131 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_131.setFont(font)
        self.label_131.setObjectName("label_131")
        self.horizontalLayout_16.addWidget(self.label_131)
        self.gridLayout_14.addLayout(self.horizontalLayout_16, 12, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 710, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 710, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 420, 101, 16))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(370, 60, 470, 340))
        self.openGLWidget.setObjectName("openGLWidget")
        #--------------------------------------------------------------#图片初始化设置
        pix = QPixmap('111.jpg')
        self.graphicsView =GraphicsView(pix,self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(370, 450, 470, 380))
        self.graphicsView.setObjectName("graphicsView")
        self.item = GraphicsPixmapItem(pix)  # 创建像素图元
        self.scene = QtWidgets.QGraphicsScene()  # 创建场景
        self.scene.addItem(self.item)
        #self.graphicsView.setScene(self.scene)  # 将场景添加至视图

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "参数选项"))
        self.label_3.setText(_translate("MainWindow", "精度等级"))
        self.comboBox.setItemText(0, _translate("MainWindow", "c"))
        self.comboBox.setItemText(1, _translate("MainWindow", "c++"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Java"))
        self.comboBox.setItemText(3, _translate("MainWindow", "python"))
        self.label_4.setText(_translate("MainWindow", "轴径【mm】"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "12"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "14"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "15"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "16"))
        self.label_10.setText(_translate("MainWindow", "导程【mm】"))
        self.comboBox_20.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_20.setItemText(1, _translate("MainWindow", "4"))
        self.comboBox_20.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_20.setItemText(3, _translate("MainWindow", "8"))
        self.label_12.setText(_translate("MainWindow", "丝杆轴材质"))
        self.label_13.setText(_translate("MainWindow", "SCM415H"))
        self.label_14.setText(_translate("MainWindow", "丝杆轴硬度"))
        self.label_15.setText(_translate("MainWindow", "滲碳58-62HRC"))
        self.label_48.setText(_translate("MainWindow", "螺母材质"))
        self.label_49.setText(_translate("MainWindow", "SCM415H"))
        self.label_50.setText(_translate("MainWindow", "螺母轴硬度"))
        self.label_51.setText(_translate("MainWindow", "滲碳58-62HRC"))
        self.label_52.setText(_translate("MainWindow", "螺母循环方式"))
        self.label_53.setText(_translate("MainWindow", "内循环"))
        self.label_69.setText(_translate("MainWindow", "螺母类型"))
        self.label_70.setText(_translate("MainWindow", "回流盖式"))
        self.label_71.setText(_translate("MainWindow", "L[mm]"))
        self.lineEdit.setText(_translate("MainWindow", "             85"))
        self.label_8.setText(_translate("MainWindow", "65mm-150m"))
        self.label_73.setText(_translate("MainWindow", "钢珠直径【mm】"))
        self.label_74.setText(_translate("MainWindow", "0.8"))
        self.label_75.setText(_translate("MainWindow", "循环圈数（圈X列）"))
        self.label_76.setText(_translate("MainWindow", "2.7X1"))
        self.label_124.setText(_translate("MainWindow", "丝杆代码"))
        self.label_125.setText(_translate("MainWindow", "SFU0504"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "精密滚珠丝杆"))
        self.label_28.setText(_translate("MainWindow", "精度等级"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "c"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "c++"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Java"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "python"))
        self.label_29.setText(_translate("MainWindow", "轴径【mm】"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "10"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "12"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "14"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "15"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "16"))
        self.label_30.setText(_translate("MainWindow", "导程【mm】"))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "4"))
        self.comboBox_23.setItemText(2, _translate("MainWindow", "6"))
        self.comboBox_23.setItemText(3, _translate("MainWindow", "8"))
        self.label_31.setText(_translate("MainWindow", "丝杆轴材质"))
        self.label_32.setText(_translate("MainWindow", "SCM415H"))
        self.label_33.setText(_translate("MainWindow", "丝杆轴硬度"))
        self.label_34.setText(_translate("MainWindow", "滲碳58-62HRC"))
        self.label_66.setText(_translate("MainWindow", "螺母材质"))
        self.label_67.setText(_translate("MainWindow", "SCM415H"))
        self.label_68.setText(_translate("MainWindow", "螺母轴硬度"))
        self.label_90.setText(_translate("MainWindow", "滲碳58-62HRC"))
        self.label_91.setText(_translate("MainWindow", "螺母循环方式"))
        self.label_92.setText(_translate("MainWindow", "内循环"))
        self.label_93.setText(_translate("MainWindow", "螺母类型"))
        self.label_94.setText(_translate("MainWindow", "回流盖式"))
        self.label_95.setText(_translate("MainWindow", "L[mm]"))
        self.lineEdit_4.setText(_translate("MainWindow", "             85"))
        self.label_35.setText(_translate("MainWindow", "65mm-150m"))
        self.label_96.setText(_translate("MainWindow", "钢珠直径【mm】"))
        self.label_97.setText(_translate("MainWindow", "0.8"))
        self.label_98.setText(_translate("MainWindow", "循环圈数（圈X列）"))
        self.label_99.setText(_translate("MainWindow", "2.7X1"))
        self.label_130.setText(_translate("MainWindow", "丝杆代码"))
        self.label_131.setText(_translate("MainWindow", "SFU0504"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "轧制滚珠丝杆"))
        self.pushButton.setText(_translate("MainWindow", "显示模型"))
        self.pushButton_2.setText(_translate("MainWindow", "导出数据"))
        self.label.setText(_translate("MainWindow", "[3D模型]"))
        self.label_2.setText(_translate("MainWindow", "[尺寸数据]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
